services:
  fitaccess-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitaccess-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 7000
      DB_HOST: 127.0.0.1
    network_mode: host

  fitaccess-email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitaccess-email-worker
    restart: unless-stopped
    command: ["npm", "run", "email:worker"]
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: 127.0.0.1
    network_mode: host

  fitaccess-billing-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitaccess-billing-worker
    restart: unless-stopped
    command: ["npm", "run", "billing:worker"]
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: 127.0.0.1
    network_mode: host

  fitaccess-onboarding-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitaccess-onboarding-worker
    restart: unless-stopped
    command: ["npm", "run", "onboarding:worker"]
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: 127.0.0.1
    network_mode: host
